apiVersion: v1
kind: ConfigMap
metadata:
  name: secondchancewebsite-config
data:
  NODE_ENV: "production"
  PORT: "9000"
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
---
apiVersion: v1
kind: Secret
metadata:
  name: secondchancewebsite-secret
type: Opaque
data:
  MONGO_PASSWORD: YWRtaW4= # base64 encoded 'admin'
  MONGO_USER: YWRtaW4= # base64 encoded 'admin'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondchancewebsite
  labels:
    app: secondchancewebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secondchancewebsite
  template:
    metadata:
      labels:
        app: secondchancewebsite
    spec:
      containers:
      - name: secondchancewebsite
        image: secondchancewebsite:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: secondchancewebsite-config
                key: NODE_ENV
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: secondchancewebsite-config
                key: PORT
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: secondchancewebsite-config
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: secondchancewebsite-config
                key: MONGO_PORT
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: secondchancewebsite-secret
                key: MONGO_USER
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secondchancewebsite-secret
                key: MONGO_PASSWORD
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: secondchancewebsite
  labels:
    app: secondchancewebsite
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: secondchancewebsite
